### ISSUE TITLE
Run integration tests on travis

### ISSUE THREAD

**Issue by qustavo** [ParadigmFoundation/go-eth#2]
When tried to enable integration tests, using [0xSnapshot](https://github.com/ParadigmFoundation/go-eth/pull/1/commits/03214c60f5c5718928a59c20220f72700ffa729b#diff-354f30a63fb0907d4ad57269548329e3R7)
 it failed because the container does not exist anymore.

**Comment by pasiphae00** [comment]
Ahh yes -- it should be at `gcr.io/zaidan-io/0x-snapshot`

I can push this up soon

**Comment by qustavo** [comment]
ok lmk
